<?php
$z[0]=Array("field","",11,37);
$z[0][4]['name']="currentstyle";
$z[1]=Array("field","",81,109);
$z[1][4]['name']="typeurl";
$z[2]=Array("field","",129,158);
$z[2][4]['name']="typename";
$z[3]=Array("channel","\r\n              <li class=\"\" data-hide=\"\"><a class=\"\" href=\"[field:typelink/]\" target=\"\"><strong>[field:typename/]</strong></a></li>\r\n              ",221,423);
$z[3][4]['type']="son";
$z[3][4]['noself']="yes";

?>