<?php
$z[0]=Array("global","\r\n                        \$a=\"\r\n                        <li class='col-4-1 last not-animated' data-animate='fadeInUp'>\";\r\n                          \$b=\"\r\n                        \r\n                        <li class='col-4-1 not-animated' data-animate='fadeInUp'>\";\r\n                          if ((@me%4)==0 && @me!=16)  @me=\$a;\r\n                          else  @me=\$b;\r\n                        ",0,450);
$z[0][4]['runphp']="yes";
$z[0][4]['name']="autoindex";
$z[1]=Array("arcurl","",566,581);
$z[2]=Array("picname","",609,625);
$z[3]=Array("title","",632,646);
$z[4]=Array("arcurl","",760,775);
$z[5]=Array("title","",793,807);

?>