<div class="col-3-1 last">
                      <div id="a1portalSkin_ctr8035280352_Column3C33A34A33_QHDCPM80352M3" class="qhd_column_contain"><!-- Start_Module_80355 --><a name="31168" id="31168"></a>
                        <div class="module-default">
                          <div class="module-inner">
                            <div id="a1portalSkin_ctr8035280352_Column3C33A34A33_ctr8035580355_mainArea" class="module-content"><!-- Start_Module_80355 -->
                              <div class="qhd-content">
                                <p style="text-align: center;"> <a href="[field:typelink /]" target="_blank"><img alt="[field:typename /]" src="/skin/img/f35d997f-04c3-457b-bcb4-e11fe40ed9b3.jpg" style="width: 313px; height: 140px;" /></a></p>
                                <p style="text-align: center;"> <a href="[field:typelink /]" target="_blank">&mdash; [field:typename /] &mdash;</a></p>
                                <p style="text-align: center;"> <span style="font-size:12px;">[field:description/]</span></p>
                              </div>
                              <!-- End_Module_80355 --></div>
                          </div>
                        </div>
                      </div>
                    </div>