<?php
$z[0]=Array("field","",317,336);
$z[0][4]['name']="title";
$z[1]=Array("global","",337,363);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",404,433);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",473,531);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",3513,3548);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",5670,5689);
$z[5][4]['name']="title";
$z[6]=Array("type"," <a href=\"[field:typelink /]\">[field:typename /]</a> ",5806,5882);
$z[7]=Array("field","",5935,5987);
$z[7][4]['name']="pubdate";
$z[7][4]['function']="MyDate('Y-m-d',@me)";
$z[8]=Array("field","",6203,6221);
$z[8][4]['name']="body";
$z[9]=Array("include","",6523,6558);
$z[9][4]['filename']="left.htm";
$z[10]=Array("include","",6672,6709);
$z[10][4]['filename']="footer.htm";
$z[11]=Array("include","",6904,6940);
$z[11][4]['filename']="right.htm";

?>