<div class="col-3-1">
                      <div id="a1portalSkin_ctr8035280352_Column3C33A34A33_QHDCPM80352M2" class="qhd_column_contain"><!-- Start_Module_80354 --><a name="31167" id="31167"></a>
                        <div class="module-default">
                          <div class="module-inner">
                            <div id="a1portalSkin_ctr8035280352_Column3C33A34A33_ctr8035480354_mainArea" class="module-content"><!-- Start_Module_80354 -->
                              <div class="qhd-content">
                                <p style="text-align: center;"> <a href="[field:typelink /]" target="_blank"><img alt="[field:typename /]" src="/skin/img/13373177-9ba3-4f7e-9b12-982011a16efd.jpg" style="width: 313px; height: 140px;" /></a></p>
                                <p style="text-align: center;"> <a href="[field:typelink /]" target="_blank">&mdash; [field:typename /] &mdash;</a></p>
                                <p style="text-align:center;"> <span style="font-size: 12px; line-height: 1.8;">[field:description/]</span></p>
                              </div>
                              <!-- End_Module_80354 --></div>
                          </div>
                        </div>
                      </div>
                    </div>