<div class="col-3-1">
                      <div id="a1portalSkin_ctr8035280352_Column3C33A34A33_QHDCPM80352M1" class="qhd_column_contain"><!-- Start_Module_80353 --><a name="31166" id="31166"></a>
                        <div class="module-default">
                          <div class="module-inner">
                            <div id="a1portalSkin_ctr8035280352_Column3C33A34A33_ctr8035380353_mainArea" class="module-content"><!-- Start_Module_80353 -->
                              <div class="qhd-content">
                                <p style="text-align: center;"> <a href="[field:typelink /]" target="_blank"><img alt="[field:typename /]" src="/skin/img/edd517a3-1d03-4f7d-a8c9-28c13a4da47e.jpg" style="width: 313px; height: 140px;" /></a></p>
                                <p style="text-align: center;"> <a href="[field:typelink /]" target="_blank">&mdash; [field:typename /] &mdash;</a></p>
                                <p style="text-align:center;"> <span style="font-size: 12px; line-height: 1.8;">[field:description/]</span></p>
                              </div>
                              <!-- End_Module_80353 --></div>
                          </div>
                        </div>
                      </div>
                    </div>