<?php
$z[0]=Array("field","",317,336);
$z[0][4]['name']="title";
$z[1]=Array("global","",337,363);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",404,433);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",473,531);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",3513,3551);
$z[4][4]['filename']="en_head.htm";
$z[5]=Array("field","",5673,5692);
$z[5][4]['name']="title";
$z[6]=Array("type","\r\n<a href=\"[field:typelink /]\">[field:typename /]</a>\r\n",5805,5883);
$z[7]=Array("field","",5937,5989);
$z[7][4]['name']="pubdate";
$z[7][4]['function']="MyDate('Y-m-d',@me)";
$z[8]=Array("field","",6230,6248);
$z[8][4]['name']="body";
$z[9]=Array("include","",6575,6613);
$z[9][4]['filename']="en_left.htm";
$z[10]=Array("include","",6726,6766);
$z[10][4]['filename']="en_footer.htm";
$z[11]=Array("include","",6963,7002);
$z[11][4]['filename']="en_right.htm";

?>