<?php
$z[0]=Array("global","",304,330);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("field","",371,400);
$z[1][4]['name']="keywords";
$z[2]=Array("global","",440,470);
$z[2][4]['name']="cfg_description";
$z[3]=Array("include","",3386,3424);
$z[3][4]['filename']="en_head.htm";
$z[4]=Array("type","<h2 style=\"text-align: center;\"> [field:typename /]</h2>\r\n                    <p style=\"text-align: center;\"> <span style=\"font-size:16px;\"><span style=\"color:#808080;\">[field:description/]</span></span></p>\r\n                    <p style=\"text-align: center;\">&nbsp; </p>\r\n                    ",5477,5793);
$z[5]=Array("field","",5815,5843);
$z[5][4]['name']="content";
$z[6]=Array("include","",6119,6159);
$z[6][4]['filename']="en_footer.htm";
$z[7]=Array("include","",6356,6395);
$z[7][4]['filename']="en_right.htm";

?>