<?php
$z[0]=Array("global","",304,330);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("field","",371,400);
$z[1][4]['name']="keywords";
$z[2]=Array("global","",440,470);
$z[2][4]['name']="cfg_description";
$z[3]=Array("include","",3382,3420);
$z[3][4]['filename']="en_head.htm";
$z[4]=Array("field","",5060,5088);
$z[4][4]['name']="content";
$z[5]=Array("type","\r\n <h2>[field:typename /]</h2>\r\n                <div class=\"module-title-content\"><i class=\"mark-left\"></i>\r\n                  <h3>[field:description/]</h3>\r\n                  <i class=\"mark-right\"></i></div>",5398,5641);
$z[5][4]['typeid']="38";
$z[6]=Array("arclist","\r\n                    <li><a href=\"javascript:;\" target=\"\"><img src=\"[field:picname/]\" height=\"84\" data-large-src=\"[field:picname/]\" alt=\"[field:title/]\" /></a></li>\r\n                    ",5975,6224);
$z[6][4]['typeid']="38";
$z[6][4]['titlelen']="80";
$z[7]=Array("include","",6586,6626);
$z[7][4]['filename']="en_footer.htm";
$z[8]=Array("include","",6823,6862);
$z[8][4]['filename']="en_right.htm";

?>