<?php
$z[0]=Array("global","",304,330);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("field","",371,400);
$z[1][4]['name']="keywords";
$z[2]=Array("global","",440,470);
$z[2][4]['name']="cfg_description";
$z[3]=Array("include","",3384,3422);
$z[3][4]['filename']="en_head.htm";
$z[4]=Array("field","",5467,5495);
$z[4][4]['name']="content";
$z[5]=Array("include","",10105,10145);
$z[5][4]['filename']="en_footer.htm";
$z[6]=Array("include","",10342,10381);
$z[6][4]['filename']="en_right.htm";

?>