<div class="col-5-1">
                      <div id="a1portalSkin_ctr8035780357_Column5C20A20A20A20A20_QHDCPM80357M1" class="qhd_column_contain"><!-- Start_Module_80358 --><a name="31171" id="31171"></a>
                        <div class="module-default">
                          <div class="module-inner">
                            <div class="module-title module-title-default clearfix">
                              <div class="module-title-content clearfix">
                                <h3 style="" class="">{dede:field name='typename'/}</h3>
                              </div>
                            </div>
                            <div id="a1portalSkin_ctr8035780357_Column5C20A20A20A20A20_ctr8035880358_mainArea" class="module-content"><!-- Start_Module_80358 --><!-- S link-line -->
                              <div class="link link-block">
                                <ul>
                                {dede:channel type='son' noself='yes' }
                                  <li><a href="[field:typelink/]" target=""><span>[field:typename/]</span></a></li>
                                  {/dede:channel}
                                 
                                </ul>
                              </div>
                              <!-- E link-line --><!-- End_Module_80358 --></div>
                          </div>
                        </div>
                      </div>
                    </div>