<?php
$z[0]=Array("global","",304,330);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("field","",371,400);
$z[1][4]['name']="keywords";
$z[2]=Array("global","",440,470);
$z[2][4]['name']="cfg_description";
$z[3]=Array("include","",3384,3419);
$z[3][4]['filename']="head.htm";
$z[4]=Array("field","",5464,5492);
$z[4][4]['name']="content";
$z[5]=Array("include","",10102,10139);
$z[5][4]['filename']="footer.htm";
$z[6]=Array("include","",10336,10372);
$z[6][4]['filename']="right.htm";

?>